language: python

python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install codecov

# script to run tests. Can also use make, e.g. "make test"
script: 
  - coverage run fraction_test.py

after_success:
  - codecov
